'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import {usePathname} from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentRoute = usePathname();
  const linkhref='flex items-center pl-[30px] pr-[30px] h-full no-underline hover:text-amber-600 duration-300';
  const activeStyle = linkhref+' text-black bg-amber-300';
  const inactiveStyle=  linkhref+' text-white';
  
 

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='h-[56px] flex justify-center item-center bg-indigo-700'>
        <Link href='/' className={(currentRoute ==='/') ? activeStyle : inactiveStyle }> HOME</Link>
        <Link href='/about' className={(currentRoute ==='/about') ? activeStyle : inactiveStyle }> ABOUT</Link>
        <Link href='/contact' className={(currentRoute ==='/contact') ? activeStyle : inactiveStyle }> CONTACT</Link>
        </nav>
        {children}</body>
    </html>
  )
}
